apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: java-quarkus-qllubhde
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/sjmrhtap/java-quarkus-qllubhde:5e1547f3865fff87329a86d05152c4bb89b0b70a
          name: container-image
